[[stack]]
name = "komodo-op"
tags = ["infrastructure", "1password-connect"]

[stack.config]
server = "docker"
poll_for_updates = true
auto_update = true
destroy_before_deploy = true
git_account = "bvierra"
repo = "bvierra/deploy-komodo-op"
branch = "main"
reclone = true
file_paths = ["docker-compose.yaml", "compose.override.yaml"]

environment = """
KOMODO_HOST=http://host.docker.internal:9120
KOMODO_API_KEY=[[KOMODO_API_KEY]]
KOMODO_API_SECRET=[[KOMODO_API_SECRET]]
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]]
OP_VAULT=[[OP_VAULT_UUID]]
OP_CREDENTIALS_BASE64=[[OP_CREDENTIALS_BASE64]]
SYNC_INTERVAL=30s
LOG_LEVEL=INFO
"""
